### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by titoesteves** [li-xinyang/OS_FrontendMaster-dl#1]
When I run python spider.py I receive the following error: 

```
bash-3.2$ python spider.py 
Downloading: Introduction None
Traceback (most recent call last):
  File "spider.py", line 237, in <module>
    download_courses(courses_detailed_data)
  File "spider.py", line 235, in download_courses
    download_file(subsection['downloadable_url'], file_path)
  File "spider.py", line 123, in download_file
    buff = urlopen(url)
  File "/Users/nestev001c/.pyenv/versions/2.7.8/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/Users/nestev001c/.pyenv/versions/2.7.8/lib/python2.7/urllib2.py", line 395, in open
    req.timeout = timeout
AttributeError: 'NoneType' object has no attribute 'timeout'
```

NOTE: In spider.py I updated the file path from `DATA_DOWNLOADABLE.json` to `DATA.json` since that is the name of the file in the directory.

I am running mac el capitan, python 2.7.8. 

Any ideas on how to resolve?

**Comment by titoesteves** [comment]
@li-xinyang is there something I need to change or update in order to get this to work?

**Comment by li-xinyang** [comment]
Sorry, I cannot test the script because I do not have a subscription right now.

Basically, what the script does is to retrieve all video `src` from HTML using beautifulsoup and write to a json file and finally download them all together.

**Comment by tranotheron** [comment]
I have the same issue. :-(

**Comment by jonsamp** [comment]
I am not able to test this, but I believe that the file `DATA.json` in the repo needs to be renamed to `DATA_DOWNLOADABLE.json`.

In **spider.py**, there's:
```py
courses_detailed_data = load_data('./DATA_DOWNLOADABLE.json')
```

Then, `load_data` is:

```py
def load_data(path):
    with open(path, 'r') as file:
        return json.loads(file.read())
```

It looks as though this function reads a file, and since `DATA_DOWNLOADABLE.json` does not exist in the repo, it reads nothing.

**Comment by li-xinyang** [comment]
The latest version solved all the previous issues.
