### ISSUE TITLE
Add support for updated UI

### ISSUE THREAD

**Issue by ebeloded** [li-xinyang/OS_FrontendMaster-dl#10]
The website had a big update this week and the script seem to be failing to find the video url.

**Comment by li-xinyang** [comment]
I do not currently have time and subscription to update the script but PR is always welcomed.

**Comment by li-xinyang** [comment]
The script is updated https://github.com/li-xinyang/OS_FrontendMaster-dl/pull/12 Thanks to @weslley39. 

Please test the new script out and report the issue.

Thanks
