### ISSUE TITLE
selenium.common.exceptions.WebDriverException

### ISSUE THREAD

**Issue by chesterheng** [li-xinyang/OS_FrontendMaster-dl#11]
What version of selenium driver you test your script with?

I keep getting Element <input id="rcp_login_submit" type="submit" value="Login"> is not clickable at point (113, 592)

**Comment by li-xinyang** [comment]
I was using the latest version of selenium python driver. However,  an issue has been reported that the script is no longer work for the updated Front-end Master UI.

https://github.com/li-xinyang/OS_FrontendMaster-dl/issues/10

**Comment by li-xinyang** [comment]
The script is updated. Please try again. Thanks
