### ISSUE TITLE
Issue when running on macOS

### ISSUE THREAD

**Issue by Nosenation** [li-xinyang/OS_FrontendMaster-dl#14]
Hi
When trying to run script on macOS I see this error:
<img width="682" alt="zrzut ekranu 2017-04-01 o 20 55 26" src="https://cloud.githubusercontent.com/assets/1431712/24581539/ab59a768-171d-11e7-90e0-452f064f398c.png">

I have Chrome
Got webdriver and added to $PATH

**Comment by vinaypuppal** [comment]
@Nosenation I solved it by running 
```bash
pip install -r requirements.txt
```

P.S Install `pip` using this guide https://pip.pypa.io/en/stable/installing/
