### ISSUE TITLE
beautifulsoup4>='4.1.3' NameError: name 'beautifulsoup4' is not defined

### ISSUE THREAD

**Issue by RAJESHW** [li-xinyang/OS_FrontendMaster-dl#2]
While running the requirements.txt module I ended in this error. Am new to Python forgive me if I'm wrong

**Comment by li-xinyang** [comment]
Make sure you have installed all the dependencies, included `pip`.

https://pypi.python.org/pypi/pip

The latest version solved all the previous issues.
