### ISSUE TITLE
Disconnected while downloading

### ISSUE THREAD

**Issue by arvi** [li-xinyang/OS_FrontendMaster-dl#20]
Is there a way to resume download where it left off when you get disconnected while downloading a course? Or do you have to repeat download all over again?

Thanks a lot. :)

**Comment by li-xinyang** [comment]
No, currently you cannot resume download from where you left off. :crying_cat_face:

**Comment by arvi** [comment]
Thanks @li-xinyang I found out it actually resumed where it left off after scanning all possible video links. :smile: It would not re-download downloaded files.

**Comment by li-xinyang** [comment]
However, I did not check for file integrity for these kinds of situation.
