### ISSUE TITLE
Selenium's NoSuchElementException terminates entire script

### ISSUE THREAD

**Issue by mstaicu** [li-xinyang/OS_FrontendMaster-dl#21]
I noticed that when the script gets to the _Table of Contents_ of a particular course and tries to access a certain video's URL and that URL is invalid, i.e. points, for example, to the course's page instead of the actual video, one gets the following error (the actual stack is bigger, but this is the most important part):

```
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"video"}
  (Session info: chrome=58.0.3029.96)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.10.5 x86_64)
```

I managed to temporarily fix this by wrapping the ```_get_video_source``` method's content in a ```try / catch```:

```
def _get_video_source(self):
        try:
            video_tag = self.browser.find_element_by_tag_name('video')
            source_link = video_tag.get_attribute('src')
            return source_link
        except Exception as e:
            pass
```

This will allow the script to finish its job and not terminate when encountering such inconsistencies in the DOM. Now, I know this might not be the most appropriate approach, but I've just wanted to raise awareness of this issue.

**Comment by li-xinyang** [comment]
I am no longer maintenance this tool but PR is welcomed.

**Comment by li-xinyang** [comment]
The latest update should already be fixed this issue with a workaround. Issue closed.
