### ISSUE TITLE
Doesn't seem to work correctly

### ISSUE THREAD

**Issue by chalmagean** [li-xinyang/OS_FrontendMaster-dl#22]
It seems that it appends the url to be fetched to the current url.

https://frontendmasters.com/courses/https:/frontendmasters.com/courses/js-fundamentals-to-functional/course-introduction

```
>>> Downloading course: https://frontendmasters.com/courses/js-fundamentals-to-functional/
Retriving: httpsfrontendmasters.comcoursesjs-fundamentals-to-functional/Objects/Course_Introduction
^C
```

**Comment by li-xinyang** [comment]
Try the newly updated script instead. Issue closed.
