### ISSUE TITLE
Wrong Video URL

### ISSUE THREAD

**Issue by roby94** [li-xinyang/OS_FrontendMaster-dl#23]
Hi there,

I was trying to download a course, everything works good, except for one video. The video url was a placeholder. Is it a bug or somnthing wrong with FEM api?

<img width="588" alt="schermata 2017-07-02 alle 13 17 44" src="https://user-images.githubusercontent.com/12794151/27769417-0a68731c-5f29-11e7-9dcc-9371bdae5a87.png">

Thank you

**Comment by li-xinyang** [comment]
Yes, this does happen only for few recent released courses. When the video DOM element cannot be found in the page, a dummy URL is produced (temp solution to make sure the script does not fail and tell me which video is not get downloaded).

I am not sure why this bug exist from FrontendMasters site. When you try to open the target video from the site it just redirect to the home page (it is the reason why the script cannot extract the URL from the DOM). 

This is the exact same issue mentioned in https://github.com/li-xinyang/OS_FrontendMaster-dl/issues/21.

**Comment by roby94** [comment]
Thank you @li-xinyang
