### ISSUE TITLE
Files are all 1k

### ISSUE THREAD

**Issue by chalmagean** [li-xinyang/OS_FrontendMaster-dl#26]
All downloaded files seem to be 1k mp4s.

```
Retriving: httpsfrontendmasters.comcourseslinting-asts/Code_Transformation_and_Linting_with_Abstract_Syntax_Trees/Introduction
Video URL: http://placehold.it/500x500
...
Downloading: Introduction
Downloading: ./Download/https://frontendmasters.com/courses/linting-asts//0-0Code_Transformation_and_Linting_with_Abstract_Syntax_TreesIntroduction.mp4
```
```
-rw-r--r--  1 me  staff   1.1K Jul 14 10:38 0-0Code_Transformation_and_Linting_with_Abstract_Syntax_TreesIntroduction.mp4
```

**Comment by li-xinyang** [comment]
Indeed that is a dirty workaround when the crawler failed to get the `video` element in the page, it just returns a dummy link (`http://placehold.it/500x500`) to prevent the script from breaking. The image is exactly 1k in size.

I have to close the issue for now and the new script may come soon. Refer issue below, https://github.com/li-xinyang/OS_FrontendMaster-dl/issues/24#issuecomment-315275295
