### ISSUE TITLE
Frontend masters using blog url in src rather than bare .mp4 video file paths

### ISSUE THREAD

**Issue by gdad-s-river** [li-xinyang/OS_FrontendMaster-dl#3]
They have recently started using blob url path instead of bare .mp4 video file paths, because of which, I think this script wouldn't work anymore (I haven't tried for sanity). I've been trying to find a way to tackle this. If @li-xinyang, you've an idea about how to go about it (after validating if this is infact true), I'd like to help make it.

![github_frontendmasters_issue](https://cloud.githubusercontent.com/assets/4655633/21422708/f05a488a-c85e-11e6-89c8-53f7e805bace.PNG)

**Comment by li-xinyang** [comment]
YouTube use the same pattern for video source (see below) but YouTube-dl is able to extract the real source from it, therefore, I believe there must be a workaround.

```
<video tabindex="-1" class="video-stream html5-main-video vsc-initialized" style="width: 854px; height: 480px; left: 0px; top: 0px; opacity: 1;" src="blob:https://www.youtube.com/e89d3c6e-e9de-43fe-9003-27f829a6ea31" data-vscid="n0ps0rf2e"></video>
```

I currently have no time and subscription to help you dig into this issue. 

https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py

Code above is the attractor for YouTube video.

**Comment by gdad-s-river** [comment]
Thanks! It was naive of me to have not researched thoroughly, I'll research upon it and update if and when I'm able to find the workaround.

**Comment by li-xinyang** [comment]
The latest version solved all the previous issues.
