### ISSUE TITLE
Not All Files in Course Are Downloading

### ISSUE THREAD

**Issue by n8sb** [li-xinyang/OS_FrontendMaster-dl#30]
Script executes fine,  but only a hand full of videos will download (followed by "Downloading: ./Download"). 

The first 3 courses I downloaded worked fine.  All are from the temporary free courses list.

<img width="520" alt="screen shot 2017-09-15 at 10 16 50 pm" src="https://user-images.githubusercontent.com/2812399/30509354-9a90d84c-9a63-11e7-97c0-49723460b7d9.png">

**Comment by n8sb** [comment]
Just discovered that during the process, the site gives back a notification that there are too many requests which assume is causing only some of the files to download.

**Comment by haopingfan** [comment]
Can the author provide an option for set certain video range inside course?
Since FrontEnd Master website has restrict max request during certain period now.
It may happen that we only download the half of course and have to wait for a while to download the others.

**Comment by li-xinyang** [comment]
I don’t have a valid subscription so I can’t do anything at the moment. You can open a PR if you can fix this.

**Comment by li-xinyang** [comment]
The code has been updated and please try the latest version to see if the issue has been fixed.
