### ISSUE TITLE
Sorry, but how do I make this work for macOS? 

### ISSUE THREAD

**Issue by KTsarlz** [li-xinyang/OS_FrontendMaster-dl#31]
I downloaded pip, and webdriver. But after that, I can't make sense of the steps. 
Can anyone provide some steps? That would be appreciated

**Comment by KTsarlz** [comment]
Now I'm having this error..
```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 1, in <module>
    import click
ImportError: No module named click
```

**Comment by li-xinyang** [comment]
You did not install dependencies properly. Please read the README again on how to install dependencies.

**Comment by KTsarlz** [comment]
@li-xinyang  I have, including the chrome drive and adding it to $PATH and installing pip with sudo and no permission error. And now, when running `python frontendmasters-dl.py` I get the error traceback.

**Comment by KTsarlz** [comment]
^ Sorry, it does now. I rebooted my laptop. Currently trying on a course.

**Comment by li-xinyang** [comment]
> How to download it at a high quality?

You have to figure it out. PR for this feature is welcomed. There is an issue mentioned abøut video quality maybe you can start from there.

**Comment by KTsarlz** [comment]
^ I'm not sure how thogh, What I do is at the start of the script. On chrome I set the quality to high, and from there it uses high quality until timeout. Now, I'm currently locked out because too many requests.

**Comment by chalmagean** [comment]
manually setting the path seems to work too `PYTHONPATH=/usr/local/lib/python2.7/site-packages python frontendmasters-dl.py`
