### ISSUE TITLE
Couldn't download workshop with OS_FrontendMaster-dl

### ISSUE THREAD

**Issue by ssanusi** [li-xinyang/OS_FrontendMaster-dl#33]
the tool is design to download only courses in the url https://frontendmasters.com/courses/COURSEID 
the workshop is in url course path i.e https://frontendmasters.com/live-event/visual-studio-code/ I tried to modify the url in spider.py but will still not work.

**Comment by li-xinyang** [comment]
Yes, you are correct. The script will not work with `live-event`. It works for regular `courses`.

**Comment by ssanusi** [comment]
is there a way this could be possible

**Comment by li-xinyang** [comment]
This is not possible to do so using the existing script because `live-event` use a different video source and which has a mechanism to validate the access user.

**Comment by harshes53** [comment]
How about the workshops that have been concluded?

**Comment by li-xinyang** [comment]
Only courses are supported because all the `live` are hosted by a different service.
