### ISSUE TITLE
All Videos are Incorrectly Saved as MP4

### ISSUE THREAD

**Issue by peritpatrio** [li-xinyang/OS_FrontendMaster-dl#35]
Some courses have videos in `webm` format, however these get saved incorrectly as `.mp4`.

**Comment by li-xinyang** [comment]
I'm not maintaining this tool at the moment but a PR to fix the issue is always welcomed. 👍

**Comment by li-xinyang** [comment]
Yes, I did hardcoded the file extension. 😓 

https://github.com/li-xinyang/OS_FrontendMaster-dl/blob/c4d068bc5acf3935c50a6144745b7521811c5401/extractor/spider.py#L177
