### ISSUE TITLE
I face this error in downloading videos

### ISSUE THREAD

**Issue by engmagdy87** [li-xinyang/OS_FrontendMaster-dl#37]
**the bash output**
>>> Login with your credential
>>> Downloading course: functional-javascript-v2
Retriving: functional-javascript-v2/Functional_JavaScript_v2/Introduction
Video URL: blob:https://frontendmasters.com/46475f19-6bce-4b20-ab20-fd347f843383
Retriving: functional-javascript-v2/Functional_Programming_Introduction/Function                                                                                                                                  al_Programming
Video URL: blob:https://frontendmasters.com/9d550a31-0415-4053-93d5-1fccdbdafec6
Retriving: functional-javascript-v2/Functional_Programming_Introduction/Provable                                                                                                                                  _and_Readable
Video URL: blob:https://frontendmasters.com/b1ccd954-7046-4a24-a0c6-da4d522f800e
Retriving: functional-javascript-v2/Functional_Programming_Introduction/Pure_Fun                                                                                                                                  ctions_and_Side-Effects
Video URL: blob:https://frontendmasters.com/ae36f2ac-8b97-4206-a3d4-69576b51ab60
Retriving: functional-javascript-v2/Functional_Programming_Introduction/Purifyin                                                                                                                                  g_Functions
Video URL: blob:https://frontendmasters.com/99f6b755-20bf-43f1-9325-dd5911b726e9
Retriving: functional-javascript-v2/Functional_Programming_Introduction/Challeng                                                                                                                                  e_1_Purify_a_Function
Video URL: blob:https://frontendmasters.com/21bc6c12-e44b-4752-908a-298b6b77f741
Retriving: functional-javascript-v2/Functional_Programming_Introduction/Challeng                                                                                                                                  e_1_Solution
Video URL: blob:https://frontendmasters.com/5af854a7-2810-4664-bb41-bc6ada3eae49
Retriving: functional-javascript-v2/Functional_Programming_Introduction/Evolving                                                                                                                                  _Understanding_of_Impurity
Video URL: blob:https://frontendmasters.com/e0cb099d-978a-451a-bee2-3c16660baf10
Retriving: functional-javascript-v2/Managing_Function_Inputs/Arguments
Video URL: blob:https://frontendmasters.com/60af0bbd-fec1-4bab-b7f9-a2300265a3f8
Retriving: functional-javascript-v2/Managing_Function_Inputs/No_Points
Video URL: blob:https://frontendmasters.com/e479a9c4-e434-48a8-9ff7-cf96fb85e1c8
Retriving: functional-javascript-v2/Managing_Function_Inputs/Challenge_2_Point-F                                                                                                                                  ree_Style
Video URL: blob:https://frontendmasters.com/e620eb2e-830a-4927-8e71-6fd81c8fdf7d
Retriving: functional-javascript-v2/Managing_Function_Inputs/Challenge_2_Solutio                                                                                                                                  n
Video URL: blob:https://frontendmasters.com/4004b0a4-1753-4e8f-8783-c110568de9c8
Retriving: functional-javascript-v2/Composing_Functions/Composition_Introduction
Video URL: blob:https://frontendmasters.com/794f4f75-a90c-44f9-8dd5-f2fcab597fce
Retriving: functional-javascript-v2/Composing_Functions/Challenge_3_Compose_and_                                                                                                                                  Pipe_Utility
Video URL: blob:https://frontendmasters.com/b98c3679-11d6-4d35-8b70-da2fc4f1601f
Retriving: functional-javascript-v2/Composing_Functions/Challenge_3_Solution
Video URL: blob:https://frontendmasters.com/e0ad22fc-be7c-4937-aced-46074497940e
Retriving: functional-javascript-v2/Immutability/Immutability_Introduction
Video URL: blob:https://frontendmasters.com/f7f64ca1-f667-4710-ae9c-ceae52415b43
Retriving: functional-javascript-v2/Immutability/Challenge_4_Compose_and_Pipe
Video URL: blob:https://frontendmasters.com/eb36692f-1edf-4a6c-9705-c1fe3ea021bc
Retriving: functional-javascript-v2/Immutability/Challenge_4_Solution
Video URL: blob:https://frontendmasters.com/d9a885d1-f06c-43df-80ef-a043f609c250
Retriving: functional-javascript-v2/Closure/Closure_and_Side_Effects
Video URL: blob:https://frontendmasters.com/aafc47bc-f4f9-4122-a7de-a734647ce8b8
Retriving: functional-javascript-v2/Closure/Challenge_5_Purifying_Closure
Video URL: blob:https://frontendmasters.com/17773c17-e3c4-4649-a28a-576850e678f6
Retriving: functional-javascript-v2/Closure/Challenge_5_Solution
Video URL: blob:https://frontendmasters.com/1f88ce2e-1e67-442d-8eee-74c52973f1d3
Retriving: functional-javascript-v2/Partial_Application/Generalized_to_Specializ                                                                                                                                  ed
Video URL: blob:https://frontendmasters.com/ea5a5734-0da1-4585-9fbd-c0e0399cc57c
Retriving: functional-javascript-v2/Recursion/Recursion_Introduction
Video URL: blob:https://frontendmasters.com/37955004-d428-4bca-8a59-201090f5e6e1
Retriving: functional-javascript-v2/Recursion/Challenge_6_Recursive_Operation
Video URL: blob:https://frontendmasters.com/22c3d204-3f3e-4501-bb68-7facee760927
Retriving: functional-javascript-v2/Recursion/Challenge_6_Solution
Video URL: blob:https://frontendmasters.com/26299bd1-a21d-4bb7-8c77-767fe9b59c24
Retriving: functional-javascript-v2/Recursion/Proper_Tail_Calls
Video URL: blob:https://frontendmasters.com/9fab523a-b5a0-4a87-a557-0f6d53b00f21
Retriving: functional-javascript-v2/Recursion/Continuation_Passing_Style
Video URL: blob:https://frontendmasters.com/272f17f5-ee0b-40cc-8047-73bb87c765ad
Retriving: functional-javascript-v2/Recursion/Trampolines
Video URL: blob:https://frontendmasters.com/ba9a1155-88ff-4492-85d4-b985dd455c00
Retriving: functional-javascript-v2/Data_Structures/List_Transformations
Video URL: blob:https://frontendmasters.com/aece641e-b479-4bbf-91c1-30015b392584
Retriving: functional-javascript-v2/Data_Structures/Filter_Exclusion
Video URL: blob:https://frontendmasters.com/c733eecd-1fac-4c35-b9ee-d44609872472
Retriving: functional-javascript-v2/Data_Structures/Reduce_Combining
Video URL: blob:https://frontendmasters.com/c86bf872-9d3c-4a8f-afd7-d22f4b00b229
Retriving: functional-javascript-v2/Data_Structures/Challenge_7_Culmination_Exer                                                                                                                                  cise
Video URL: blob:https://frontendmasters.com/41434878-bf99-4cfc-a882-8afdaee0e102
Retriving: functional-javascript-v2/Data_Structures/Challenge_7_Solution
Video URL: blob:https://frontendmasters.com/95c22be2-0c14-42ff-a0c2-73e1b33c1724
Retriving: functional-javascript-v2/Data_Structures/Challenge_7_Solution_2
Video URL: blob:https://frontendmasters.com/afc373a1-6548-4e8e-8ce5-865500d5ddaa
Retriving: functional-javascript-v2/Data_Structures/Challenge_7_Solution_3
Video URL: blob:https://frontendmasters.com/29a66127-9d75-40bd-a543-1d083f76ee5e
Retriving: functional-javascript-v2/Data_Structures/Fusion
Video URL: blob:https://frontendmasters.com/331ce154-fc28-45a3-b96f-9e38e5eb3d9d
Retriving: functional-javascript-v2/Data_Structures/Transducing
Video URL: blob:https://frontendmasters.com/74966ff9-0dfd-4275-af98-a06140b72bed
Retriving: functional-javascript-v2/Data_Structure_Operations/Data_Structure_Ope                                                                                                                                  rations_Introduction
Video URL: blob:https://frontendmasters.com/d12393ab-3539-4b14-829b-03ef439be5fd
Retriving: functional-javascript-v2/Data_Structure_Operations/Challenge_8_Culmin                                                                                                                                  ation_Exercise_2
Video URL: blob:https://frontendmasters.com/1d3b2182-6f97-4b72-8feb-3280dadc2d2c
Retriving: functional-javascript-v2/Data_Structure_Operations/Challenge_8_Soluti                                                                                                                                  on
Video URL: blob:https://frontendmasters.com/f0a69641-5625-4ba5-857f-6128e11acdbd
Retriving: functional-javascript-v2/Functional_Programming_Utility/FPO.js
Video URL: blob:https://frontendmasters.com/65616556-6bca-439c-a046-9a3bb2b0cf7d
Retriving: functional-javascript-v2/Async_Programming/Lazy_Arrays
Video URL: blob:https://frontendmasters.com/cc0b15fa-e5c7-4529-b9a2-2a86e2fc204d
Retriving: functional-javascript-v2/Async_Programming/Challenge_9_Observables
Video URL: blob:https://frontendmasters.com/be25b1a2-5e77-4ae9-bdeb-b077f46d0073
Retriving: functional-javascript-v2/Async_Programming/Challenge_9_Solution
Video URL: blob:https://frontendmasters.com/8bea72a8-5840-406d-894f-6ba1423e4685
Retriving: functional-javascript-v2/Wrapping_Up_Functional_JavaScript_v2/Wrappin                                                                                                                                  g_Up
Video URL: blob:https://frontendmasters.com/02315506-1b5a-44f0-9084-dbc3593d8f52
Downloading: Introduction
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "C:\Python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.download(course)
  File "C:\Users\MM\Downloads\New folder\OS_FrontendMaster-dl\extractor\spider.p                                                                                                                                  y", line 45, in download
    self.download_course(course_downloadbale)
  File "C:\Users\MM\Downloads\New folder\OS_FrontendMaster-dl\extractor\spider.p                                                                                                                                  y", line 181, in download_course
    download_file(subsection['downloadable_url'], file_path, self)
  File "C:\Users\MM\Downloads\New folder\OS_FrontendMaster-dl\extractor\helper.p                                                                                                                                  y", line 24, in download_file
    buff = urlopen(temporaryURL)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 452, in _open
    'unknown_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1266, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: blob>

**Comment by li-xinyang** [comment]
The tool is not supported for Window because I wrote all the path in Unix way. You might need to some changes to the path.

**Comment by li-xinyang** [comment]
Please try the tool again as @darlenedms make a PR to fix this in Window OS.

**Comment by denvercoder** [comment]
Sorry, I keep posting in the wrong area.

I'm having a similar issue, I can't download the course with the course id:
full-stack-v2

but I was able to download

full-stack

just fine.

I'm on OSX High Sierra

It looks to me like maybe the structure of the URLS has changed and its confusing the script. It seems like the older courses download better than the newer ones.

Video URL: blob:https://frontendmasters.com/ee833872-c072-41ee-9275-8d1a307809c3
Downloading: Introduction
Traceback (most recent call last):
File "frontendmasters-dl.py", line 24, in
downloader()
File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in call
return self.main(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "frontendmasters-dl.py", line 17, in downloader
spider.download(course, high_resolution, video_per_video)
File "/Users/dev/OS_FrontendMaster-dl/extractor/spider.py", line 56, in download
self.download_course(course_downloadbale)
File "/Users/dev/OS_FrontendMaster-dl/extractor/spider.py", line 219, in download_course
self.download_video(i1, i2, subsection, section_title, course_path)
File "/Users/dev/OS_FrontendMaster-dl/extractor/spider.py", line 230, in download_video
download_file(subsection['downloadable_url'], file_path)
File "/Users/dev/OS_FrontendMaster-dl/extractor/helper.py", line 52, in download_file
buff = urlopen(url)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
response = self._open(req, data)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 454, in _open
'unknown_open', req)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1265, in unknown_open
raise URLError('unknown url type: %s' % type)
urllib2.URLError:
