### ISSUE TITLE
DATA_DOWNLOADABLE error 

### ISSUE THREAD

**Issue by it-sumanp** [li-xinyang/OS_FrontendMaster-dl#4]
Traceback (most recent call last):
  File "spider.py", line 183, in <module>
    courses_data = load_data('./DATA_DOWNLOADABLE.json')
  File "spider.py", line 160, in load_data
    with open(path, 'r') as file:
IOError: [Errno 2] No such file or directory: './DATA_DOWNLOADABLE.json'

**Comment by li-xinyang** [comment]
The script is no longer working. Will update when next I subscribe the service.
