### ISSUE TITLE
Unknown URL Type: blob>

### ISSUE THREAD

**Issue by rdrunner74** [li-xinyang/OS_FrontendMaster-dl#44]
Everything installed correctly, the program runs through the videos.

Retriving: functional-javascript-v2/Wrapping_Up_Functional_JavaScript_v2/Wrapping_Up
Video URL: blob:https://frontendmasters.com/da8ad72b-4368-4be8-a6f5-67fd463afffd

**But then it encounters this error.**

urllib2.URLError: <urlopen error unknown url type: blob

Any ideas?

**Comment by exitudio** [comment]
I got this error because of wrong password and it took me to the guess page. It completed crawling to all videos but cannot load that videos.

**Comment by li-xinyang** [comment]
I think the reason is been locked out due to too many requests been made in limited amount of time

**Comment by li-xinyang** [comment]
Please try the latest version. Close issue.
