### ISSUE TITLE
high_resolution no class_name "fm-vjs-quality"

### ISSUE THREAD

**Issue by exitudio** [li-xinyang/OS_FrontendMaster-dl#45]
I got this error when I set the options --high-resolution
```
selenium.common.exceptions.NoSuchElementException: 
Message: no such element: Unable to locate element: 
{"method":"class name","selector":"fm-vjs-quality"}
```

The problem is there is no class name "fm-vjs-quality" in some cases.

P.S.
@KrzysztofKarol It's from your last PR. I don't want to step on your feet. But if you want me to fix that just let me know.

**Comment by li-xinyang** [comment]
`fm-vjs-quality` seems like random generated `className`

**Comment by KrzysztofKarol** [comment]
@exitudio Could you tell me what course is that or what class has this element in your case
![image](https://user-images.githubusercontent.com/12470911/33479443-6d9cbbd8-d68d-11e7-85da-a859d98d8ba1.png)

**Comment by exitudio** [comment]
Oh, I tried it again. It seem like, I typed the wrong password then it took me to the guess page which there is only one resolution.

![image](https://user-images.githubusercontent.com/3590976/33492736-02082ba6-d68c-11e7-8ca3-59d92eb8cdc5.png)
