### ISSUE TITLE
Course missing from list

### ISSUE THREAD

**Issue by pjrashidi** [li-xinyang/OS_FrontendMaster-dl#5]
There's a new course at this address that's missing from the list. https://frontendmasters.com/courses/complete-intro-react/

I tried to add the course and URL to the DATA_COURSE_LIST.json file and it doesn't do anything. Not sure how to add it to DATA_COURSE_DETAILED_LIST_CDN.json file.

**Comment by bhagatparwinder** [comment]
@pjrashidi I believe you have to add the course details in DATA_COURSE_DETAILED_LIST.json as well

**Comment by li-xinyang** [comment]
`DATA_COURSE_LIST` and `DATA_COURSE_DETAILED_LIST_CDN` files are fetched using clowder. 

You can re-fetch (auto generated after fetching) these files by deleting them.
