### ISSUE TITLE
Message: 'chromedriver' executable needs to be in PATH.

### ISSUE THREAD

**Issue by boonyao1122** [li-xinyang/OS_FrontendMaster-dl#66]
hello, I am new to python or selenium. Apologise for the fool question and appreciate for your help.

After i download chromedriver, paste it same directory in the root folder. I double click run chromedriver first, then run the frontendmaster-dl.py script and i got this error.
<img width="1219" alt="screen shot 2018-02-03 at 6 19 00 pm" src="https://user-images.githubusercontent.com/19177931/35766230-c27ba426-090e-11e8-98fe-945bea38481a.png">

Please help.

**Comment by li-xinyang** [comment]
Try to setup the `chromedrive` by following the steps here, https://sites.google.com/a/chromium.org/chromedriver/getting-started

**Comment by boonyao1122** [comment]
Hi xinyang, thank you for you fast replying. I have been go thru the link you provided and realise i need to include the path to ChromeDriver when instantiating webdriver.Chrome. This is how i do it but the outcome still fail. 
<img width="761" alt="screen shot 2018-02-04 at 1 15 21 am" src="https://user-images.githubusercontent.com/19177931/35769682-5df71ce8-0949-11e8-8be4-3bf000f1c735.png">

What did i missing? Please guide. Thanks.

**Comment by li-xinyang** [comment]
whats the new errro? are you using macOS, if so install the chrome drive using homebrew instead?

Otherwise, try to add the your chrome drive to system path, https://stackoverflow.com/questions/7703041/editing-path-variable-on-mac

**Comment by boonyao1122** [comment]
Hi Sir,
Yes i am using macOS and after install chrome drive using homebrew, the error has solved.
And I bumped into new error again. gosh.

>>> Login with your credential
>>> Downloading course: https://frontendmasters.com/courses/responsive-email/
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 28, in <module>
    downloader()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 21, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/leeyaoyao/Desktop/frontendMaster/OS_FrontendMaster-dl/extractor/spider.py", line 49, in download
    course_detailed_list = self._get_detailed_course_list(course)
  File "/Users/leeyaoyao/Desktop/frontendMaster/OS_FrontendMaster-dl/extractor/spider.py", line 75, in _get_detailed_course_list
    sections_items = sections.find_all(
AttributeError: 'NoneType' object has no attribute 'find_all'

Do u have any idea on it?

**Comment by TheDreamSaver** [comment]
Getting the same error @li-xinyang  even after doing what @boonyao1122  did in the above screenshot.
