### ISSUE TITLE
problem with click

### ISSUE THREAD

**Issue by denvercoder** [li-xinyang/OS_FrontendMaster-dl#69]
keep getting this error

$ python frontendmasters-dl.py
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 1, in <module>
    import click
ImportError: No module named click

click is installed successfully

Requirement already satisfied: click in /private/var/root/Library/Python/2.7/lib/python/site-packages (from -r requirements.txt (line 4))

**Comment by mszczepaniak** [comment]
How did you resolve that issue? I am getting the same problem.
