### ISSUE TITLE
Can't download elm/beginning-elm course

### ISSUE THREAD

**Issue by romariolopezc** [li-xinyang/OS_FrontendMaster-dl#72]
The URL is different from the other courses.

`firebase-react` -> `elm/beginning-elm`

https://frontendmasters.com/courses/elm/beginning-elm/

**Comment by romariolopezc** [comment]
How to solve this?

**Comment by li-xinyang** [comment]
Change the URL capture pattern might fix this issue. 

https://github.com/li-xinyang/OS_FrontendMaster-dl/blob/master/extractor/spider.py#L65
