### ISSUE TITLE
ImportError: No module named click

### ISSUE THREAD

**Issue by eldyvoon** [li-xinyang/OS_FrontendMaster-dl#79]
I got this error although I already did `pip install`

```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 1, in <module>
    import click
ImportError: No module named click
```

I'm using python 3, does it matter?

**Comment by li-xinyang** [comment]
in this case, it is because you have unresolved dependency 'click', the script is for Python 2.

**Comment by eldyvoon** [comment]
so I have to downgrade python 3 to version 2?

**Comment by li-xinyang** [comment]
You need to install dependencies first before you start using the tool. and you actually can have multiple version of Python on the machine so technically you do not need to downgrade Python version.

**Comment by mitrikyle** [comment]
That probably means you mistyped the course name.

**Comment by eldyvoon** [comment]
@mitrikyle course name is optional, right? I gave `javascript-foundations` as Course Id
