### ISSUE TITLE
this script supports stop and continue download?

### ISSUE THREAD

**Issue by xfilipe** [li-xinyang/OS_FrontendMaster-dl#8]
I'm getting some corrupted files (mainly when I interrupt the script) and the video is not being downloaded again, because of the huge number of videos its hard to check every video manually maybe is a good idea to have some integrity check.

**Comment by li-xinyang** [comment]
Currently, the feature is not supported. How the script work is to fetch the video CDN (video source) link from the site, save it, and then download them one after another.

You can change the script inside `download` method OR write your own `download` method which use the CDN file to make this feature available to you.
