### ISSUE TITLE
Cannot use chrome driver 

### ISSUE THREAD

**Issue by okyanusatlas** [li-xinyang/OS_FrontendMaster-dl#9]
After installing the driver  ,when I open it I cant type anything, and I got the notification ' only local connections are allowed

**Comment by li-xinyang** [comment]
Can you specify how you install the web driver?

**Comment by okyanusatlas** [comment]
Also I downloaded the  chrome web driver from the link you posted. I cant use that at all. When I try python commandline  and type pip install -r requirements.txt , I get this message : SyntaxError : invalid syntax

**Comment by okyanusatlas** [comment]
![resim](https://cloud.githubusercontent.com/assets/24398340/24323347/85c2e4aa-1174-11e7-83cd-d6aabbf451b5.png)


A screenshot here.

**Comment by okyanusatlas** [comment]
Okay I solved the problem. But how can I run run.py on Windows machine?

**Comment by okyanusatlas** [comment]
Also solved.  Now script is running in background, viewing all the videos one by one, but the download folder is not created no where. and I guess it is not downloading anything right now.

**Comment by li-xinyang** [comment]
Check `DATA_COURSEDETAILED_LIST_CDN.json` see if video links are there.

**Comment by okyanusatlas** [comment]
Unfortunately, all 'downloadable url's are at  null

**Comment by li-xinyang** [comment]
The scrip

**Comment by KTsarlz** [comment]
@okyanusatlas How did you make it work on windows 10?

**Comment by li-xinyang** [comment]
For those who have the issue with Chrome drive. I'm thinking using Headless Chrome to do this will be much better and faster and fewer dependencies to manage. 

If you are interested and have a subscription, feel free to recreate a new script and I am happy to review the code for you.
